stages:
- stage: BuildBackendServices

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildDotnetBackend
    steps:
    - task: DotNetCoreCLI@2
      name: BuildDotNetApp
      inputs:
        command: 'build'
        projects: '**/MyFirstAzureWebApp/MyFirstAzureWebApp.csproj'
    - task: DotNetCoreCLI@2
      name: PublishDotNetApp
      inputs:
        command: 'publish'
        publishWebProjects: true
    - task: AzureWebApp@1
      name: DeploytoWebApp
      inputs:
        azureSubscription: 'sub-06(82fec995-d706-4757-a002-6bfc2d89631a)'
        appType: 'webApp'
        appName: 'mf01dev'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deploymentMethod: 'zipDeploy'
  
  - job: BuildDockerService
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '**/SalesBook.LB/Dockerfile'