stages:
- stage: BuildBackendServices

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildDotnetBackend
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/MyFirstAzureWebApp/MyFirstAzureWebApp.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'sub-06(82fec995-d706-4757-a002-6bfc2d89631a)'
        appType: 'webApp'
        appName: 'mf01dev'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deploymentMethod: 'zipDeploy'